/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
// biome-ignore lint: disable
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    CoButton: typeof import('./src/components/co-button/index.vue')['default']
    CoColorInput: typeof import('./src/components/co-input/co-color-input.vue')['default']
    CoFileInput: typeof import('./src/components/co-file-input/index.vue')['default']
    CoInput: typeof import('./src/components/co-input/index.vue')['default']
    CoProgress: typeof import('./src/components/co-progress/index.vue')['default']
    CoRadioGroup: typeof import('./src/components/co-radio-group/index.vue')['default']
    CoSettingsPanel: typeof import('./src/components/co-settings-panel/index.vue')['default']
    CoShadowInput: typeof import('./src/components/co-input/co-shadow-input.vue')['default']
    ElCollapse: typeof import('element-plus/es')['ElCollapse']
    ElCollapseItem: typeof import('element-plus/es')['ElCollapseItem']
    ElDialog: typeof import('element-plus/es')['ElDialog']
    ElProgress: typeof import('element-plus/es')['ElProgress']
    ElScrollbar: typeof import('element-plus/es')['ElScrollbar']
    IconArrowDown: typeof import('./src/components/co-settings-panel/components/icon-arrow-down.vue')['default']
    IconImage: typeof import('./src/components/co-file-input/components/icon-image.vue')['default']
  }
}
